### ISSUE TITLE
least_angle.py in lars_path: ValueError: operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by cod3licious** [cod3licious/autofeat#1]
Known issue related to sklearn bug: https://github.com/scikit-learn/scikit-learn/issues/9603
Sometimes (randomly) during the feature selection process, the LassoLARS model crashes with an error like this
```
.../lib/python3.6/site-packages/sklearn/linear_model/least_angle.py in lars_path(X, y, Xy, Gram, max_iter, alpha_min, method, copy_X, eps, copy_Gram, verbose, return_path, return_n_iter, positive)
    378                                  least_squares)
    379 
--> 380         g1 = arrayfuncs.min_pos((C - Cov) / (AA - corr_eq_dir + tiny32))
    381         if positive:
    382             gamma_ = min(g1, C / AA)

ValueError: operands could not be broadcast together with shapes (397,) (396,)
```

Try updating your sklearn and numpy versions; otherwise I'm afraid there is not much that could be done here.

**Comment by Muhammad4hmed** [comment]
I updated the numpy and sklearn but still the same issue. can you tell me what to do ?

**Comment by cod3licious** [comment]
As of version 1.0.0 this error should be caught in most cases, so please update with `pip install --upgrade autofeat`. Please note that there are now two autofeat models available, `AutoFeatRegressor` and `AutoFeatClassifier` for regression and classification problems respectively.
