### ISSUE TITLE
ImportError: cannot import name 'AutoFeatRegressor' from 'autofeat'

### ISSUE THREAD

**Issue by VaibhavKharare** [cod3licious/autofeat#11]
ImportError: cannot import name 'AutoFeatRegressor' from 'autofeat'

**Comment by cod3licious** [comment]
Did you install (and/or upgrade) the library via pip? Otherwise if you downloaded the repository, you may need to add the correct folder (the autofeat folder inside the repository autofeat folder) to your python path

**Comment by VaibhavKharare** [comment]
> Did you install (and/or upgrade) the library via pip? Otherwise if you downloaded the repository, you may need to add the correct folder (the autofeat folder inside the repository autofeat folder) to your python path

Thanks for a quick revert! I installed it using pip in an anaconda environment.

**Comment by VaibhavKharare** [comment]
Hey! Update: I tried to clean the site-packages directory (using conda clean --packages) and autofeat works now. Thanks :)

**Comment by VaibhavKharare** [comment]
![image](https://user-images.githubusercontent.com/54493220/81318725-4be07f80-90ac-11ea-8bda-d995854a79ec.png)

**Comment by VaibhavKharare** [comment]
![image](https://user-images.githubusercontent.com/54493220/81318830-74687980-90ac-11ea-8e4b-3dada6444e61.png)

**Comment by cod3licious** [comment]
Is this your script that is called `autofeat.py`? Not sure but maybe Python tries to import it from your script instead of the actual library because you're working in this folder? 
Did you restart your kernel after cleaning the packages?
If all else fails, you can also download the repository and put the autofeat folder from the repository (not the whole repository itself) in the folder where you're currently working in...

**Comment by VaibhavKharare** [comment]
> Is this your script that is called `autofeat.py`? Not sure but maybe Python tries to import it from your script instead of the actual library because you're working in this folder?
> Did you restart your kernel after cleaning the packages?
> If all else fails, you can also download the repository and put the autofeat folder from the repository (not the whole repository itself) in the folder where you're currently working in...

Hey! This was so silly of me. I have renamed my working file and the issue is now fixed. Thanks again for your help!
