### ISSUE TITLE
AttributeError: module 'sympy.core.core' has no attribute 'add'

### ISSUE THREAD

**Issue by vin2015-edem** [cod3licious/autofeat#18]
After updating your library, my public notebook [Titanic - Autofeat (automatic FE)](https://www.kaggle.com/vbmokin/titanic-autofeat-automatic-fe) for selecting features for solving the task in the Kaggle Competition ["Titanic - Machine Learning from Disaster"](https://www.kaggle.com/c/titanic) stopped working.
[Early](https://www.kaggle.com/vbmokin/titanic-autofeat-automatic-fe?scriptVersionId=28320249) (a year ago) this code worked successfully (autofeat-0.2.5):
```
model = AutoFeatRegression()
X_train_feature_creation = model.fit_transform(train.to_numpy(), target.to_numpy().flatten())
X_test_feature_creation = model.transform(test.to_numpy())
```

[Now](https://www.kaggle.com/vbmokin/titanic-autofeat-automatic-fe?scriptVersionId=51887084) I outputs an error (autofeat-2.0.4):
```
model = AutoFeatRegressor()
X_train_feature_creation = model.fit_transform(train.to_numpy(), target.to_numpy().flatten())
X_test_feature_creation = model.transform(test.to_numpy())

```
I've tried this as well:
```
X_train_feature_creation = model.fit_transform(train, target)
X_test_feature_creation = model.transform(test)
```
and:
```
model.fit(train, target)
```
I got the same error.

Thanks in advance for the advice on how to fix this.

**Comment by cod3licious** [comment]
updating sympy to the latest version should fix this, can you please test this?

**Comment by cod3licious** [comment]
I've also updated the autofeat version to 2.0.5 and added the current sympy version as a must have so if you update autofeat again it should now also update sympy to the latest version

**Comment by vin2015-edem** [comment]
> updating sympy to the latest version should fix this, can you please test this?

Thanks!
I try it: https://www.kaggle.com/vbmokin/titanic-autofeat-automatic-fe?scriptVersionId=51958973
