### ISSUE TITLE
theoretical Question

### ISSUE THREAD

**Issue by lachhebo** [cod3licious/autofeat#2]
I have a question: 

Does the features created by autofeat could be as efficient if used in an other ML algorithm or in a classification problem ?

**Comment by cod3licious** [comment]
The resulting features could definitely be used as input for another algorithm as well!

Concerning the classification problem: The model is supposed to be used for problems with a single target variable. This means that you could in principle also use it for a binary classification problem (i.e. if your labels are only 0 and 1), but it doesn't make sense for multiclass problems, unless you frame them as a one-vs-rest binary classification task for each of the classes - but this will probably get pretty messy if you have more than a handful of classes.
