### ISSUE TITLE
Is it possible to use autofeat without exceeding memory of the system?

### ISSUE THREAD

**Issue by gautambak** [cod3licious/autofeat#20]
i.e. does autofeat work on vaex or dask?

**Comment by cod3licious** [comment]
@gautambak no, unfortunately not (yet - pull requests are of course very welcome!). But for the normal AutoFeatRegressor/Classifier you can set the argument `max_gb` to the number of gigabytes of RAM that you have available. It wont respect that 100% but will downsample your data before the feature engineering step to a number such that the matrix n_datapoints x n_features_after_feateng should take up less GB than specified and then in the end, after the feature selection, all your data will be transformed using only the features that were formed. But you might also want to do the downsampling yourself to make sure that the whole range of values for each feature is present in the downsampled data and/or specify to use only some of the features for the feature engineering process.

**Comment by gautambak** [comment]
thank you very much @cod3licious I'll give it a try and report back! I'll have to experiment with it until I understand it better.

By the way, I saw your youtube video from pyBerlin, It is really good and you explained the use case & trade-offs so clearly. Thank you!

**Comment by gautambak** [comment]
Thank you it worked!
