### ISSUE TITLE
How to transform new data?

### ISSUE THREAD

**Issue by Antitesla** [cod3licious/autofeat#22]
Does this library have some methods to transform new dataset to dataset with additional features generated before?

So I need to make this steps:
1) Generate additional features for my dataset.
2) Save transformation matrix.
3) Apply transformation matrix on new dataset to predict it.

Is it now possible?

**Comment by cod3licious** [comment]
Yes, after calling `.fit()` or `.fit_transform()` on the model with your initial dataset to determine which additional features should be used, you can then call `.transform()` on the model with new data to compute the additional features for other samples. Have a look at the example notebooks where this is also demonstrated.
