### ISSUE TITLE
pandas corr is too slow; use numpy instead

### ISSUE THREAD

**Issue by stepthom** [cod3licious/autofeat#28]
When running on a medium dataset (~50K instances, ~35 features), I noticed that `autofeat`'s `AutoFeatLight` was taking hours and hours to complete. After debugging a bit, the bottleneck was the line:

https://github.com/cod3licious/autofeat/blob/d08dd474919236c3a78087700051da31645d1e7a/autofeat/autofeatlight.py#L35

When I replaced it with Numpy, the code ran orders of magnitude faster:

```python
    corrmat = pd.DataFrame(np.abs(np.corrcoef(df.values, rowvar=False)), columns=df.columns)
```

**Comment by cod3licious** [comment]
Thanks @stepthom, nice catch! The change is live in version 2.0.9
