### ISSUE TITLE
ufunc '_lambdifygenerated' did not contain a loop with signature matching types (<class 'numpy.dtype[float32]'>, <class 'numpy.dtype[float32]'>) -> None

### ISSUE THREAD

**Issue by LiuZhenkun-DUFE** [cod3licious/autofeat#33]
Hi, Drs,
X_train and y_train are Dataframe of array of Float64 when I use the following code:

        alldata1= sio.loadmat(path)['input_train'].ravel()
        x_train=pd.DataFrame(alldata1[folds])
        x_train.columns=input_new_columns
        alldata2= sio.loadmat(path)['output_train'].ravel()
        y_train=pd.DataFrame(alldata2[folds])
        y_train.columns=['targat']
        alldata3= sio.loadmat(path)['input_test'].ravel()
        x_test=pd.DataFrame(alldata3[folds])
        x_test.columns=input_new_columns
        alldata4= sio.loadmat(path)['output_test'].ravel()
        y_test=pd.DataFrame(alldata4[folds])
        y_test.columns=['targat']
        alldata5= sio.loadmat(path)['input_vaildation'].ravel()
        x_validation=pd.DataFrame(alldata5[folds])
        x_validation.columns=input_new_columns
        alldata6= sio.loadmat(path)['output_vaildation'].ravel()
        y_validation=pd.DataFrame(alldata6[folds])
        y_validation.columns=['targat']
        afreg = AutoFeatClassifier(feateng_steps=2,categorical_cols=sparse_new_columns)
        x_train_tr = afreg.fit_transform(x_train, y_train)

 but I find an error: 
UFuncTypeError ufunc '_lambdifygenerated' did not contain a loop with signature matching types (&lt; class 'numpy.dtype[float32]'&gt; , &lt; class 'numpy.dtype[float32]'&gt;) -&gt; None

May I ask what causes this?

**Comment by cod3licious** [comment]
Could you please post the complete traceback of the error message and also show a screenshot of what `x_train` and `y_train` look like? Thanks :)

**Comment by LiuZhenkun-DUFE** [comment]
![fig1](https://user-images.githubusercontent.com/72729382/155844560-3ac14027-7e7b-4da7-9c1c-806ce5e9f86e.png)
Fig.1 is the complete traceback of the error message
And figs2-5 denote the details of x_train and y_train.
![fig4](https://user-images.githubusercontent.com/72729382/155844564-b9d0bee5-6b69-485f-9a2d-b5d89b53bf43.png)
![fig5](https://user-images.githubusercontent.com/72729382/155844566-e57d24b1-b1d1-43b0-a4c1-1fc8608f6801.png)
![fig3](https://user-images.githubusercontent.com/72729382/155844569-0b00318e-2595-4b02-be57-78ed584d9030.png)
![fig2](https://user-images.githubusercontent.com/72729382/155844572-7a5c2e49-53b1-416f-bb4e-289650ff88fa.png)

In addition to this, the version of numpy is 1.22.2

Looking forward to your professional advice!

Best Wishes,

**Comment by cod3licious** [comment]
Have you tried running it with a numpy version 1.21.*? It might be related to [this issue](https://github.com/numpy/numpy/issues/20735)...

**Comment by LiuZhenkun-DUFE** [comment]
Oh my god, your opinion is very effective to me, thank you very much for your opinion!

**Comment by LiuZhenkun-DUFE** [comment]
It really works!
