### ISSUE TITLE
How to choose sin(x) and cos(x) etl. as features?

### ISSUE THREAD

**Issue by TUM-Luka-Lu** [cod3licious/autofeat#35]
Hi,

first of all thanks for the super libary.
I would like to ask, how can i get sin(x) or cos(x) also as features?
Such as i have a target func: (x-np.sqrt(2))*(np.sin(8*np.pi*x))**2

BR

**Comment by riebay** [comment]
Hi Luka,
you can give the transformations that you would like to apply to autofeat in the initialization with the "transformations" Keyword. 

E.g. instatiate your regressor with 

afreg = AutoFeatRegressor(verbose=1, feateng_steps=steps, transformations=["sin", "cos", "sqrt"])

To have a look, which transformations are implemented, check the feateng.py module.

Happy Computing
