### ISSUE TITLE
Scaling and Autofeat

### ISSUE THREAD

**Issue by fitzpk** [cod3licious/autofeat#36]
Thank you for the awesome library.

Just have a question about feature scaling, I've read that features need to be scaled BEFORE using autofeat (https://analyticsindiamag.com/guide-to-automatic-feature-engineering-using-autofeat/). 

Is this true? I can't seem to find information in the repository that supports this statement.

When running autofeat is seems to perform scaling during feature selection so I am just wondering if I have to do scaling beforehand or if I can just throw my data into autofeat and it is taken care of.
<img width="620" alt="Screen Shot 2023-02-24 at 12 24 55 PM" src="https://user-images.githubusercontent.com/24630000/221246950-53017256-e244-449c-a28c-cdcde51809bf.png">

**Comment by cod3licious** [comment]
Yes, you are absolutely right, feature scaling before is not required. In fact it is usually beneficial to use the original features in the feature engineering step, especially if these represent physical quantities, to compute new features with meaningful ratios etc.

**Comment by fitzpk** [comment]
Perfect, thank you for clearing the air on this - really appreciate it!
