### ISSUE TITLE
[enhancement] add predict_proba for classifiers

### ISSUE THREAD

**Issue by mglowacki100** [cod3licious/autofeat#37]
Autofeat provides only `predict` for classification problems, it should also provide `predict_proba` for use cases when we're not interested in 'hard prediction' but 'ranking'. I think it should be hard to expose it from underlying sklearn models.

**Comment by cod3licious** [comment]
Great idea! Unfortunately, I don't know when I'll get to that, but pull requests are always welcome!

**Comment by mglowacki100** [comment]
Hi
@cod3licious cod3 as far I see and after running local test it seems enough to add method `predict_proba` as minimally modified `predict` method to `class AutoFeatModel(BaseEstimator)`

```
    def predict_proba(self, X):
        """
        Inputs:
            - X: pandas dataframe or numpy array with original features (n_datapoints x n_features)
        Returns:
            - y_pred: predicted targets probs return by prediction_model.predict_proba()
        """
        check_is_fitted(self, ["prediction_model_"])
        # store column names as they'll be lost in the other check
        cols = [str(c) for c in X.columns] if isinstance(X, pd.DataFrame) else []
        # check input variables
        X = check_array(X, dtype=None)
        if not cols:
            cols = ["x%03i" % i for i in range(X.shape[1])]
        # transform X into a dataframe (again)
        df = pd.DataFrame(X, columns=cols)
        # do we need to call transform?
        if not list(df.columns) == self.all_columns_:
            temp = self.always_return_numpy
            self.always_return_numpy = False
            df = self.transform(df)
            self.always_return_numpy = temp
        return self.prediction_model_.predict_proba(df[self.good_cols_].to_numpy())
```
I'll try to make proper PR in the coming week.

**Comment by mglowacki100** [comment]
Here is PR:
https://github.com/cod3licious/autofeat/pull/38

**Comment by mglowacki100** [comment]
Hi @cod3licious,
Maybe, I miss something obvious but I don't see any comments/reviews for this PR :(

**Comment by cod3licious** [comment]
@mglowacki100 this is what it looks like for me:

<img width="1563" alt="Screenshot 2023-05-05 at 09 40 01" src="https://user-images.githubusercontent.com/1093567/236402215-8d457416-ca83-4bba-8984-cea550341a34.png">

**Comment by mglowacki100** [comment]
@cod3licious I think 'Pending' status of review is misleading (https://github.com/orgs/community/discussions/10369)
On my side I see it like this:
![autofeat_git](https://user-images.githubusercontent.com/6077538/236411115-9ec6dc49-a3b4-4edd-9e8c-9963c1b36d94.PNG)

**Comment by cod3licious** [comment]
wow, what a horrible UX. sorry, now you should see it

**Comment by cod3licious** [comment]
Thanks so much, I merged the changes and will release a new version next weekend (since I also wanted to make sure the code works with the new sklearn versions and everything)

**Comment by cod3licious** [comment]
@mglowacki100 you should now be able to install version 2.1.0 with the predict_proba function using `pip install --upgrade autofeat` - please let me know if there are any problems :)

**Comment by mglowacki100** [comment]
@cod3licious Thanks, it works correctly :)
