### ISSUE TITLE
ValueError: Input X contains NaN.

### ISSUE THREAD

**Issue by sauravsingh243** [cod3licious/autofeat#40]
afreg = AutoFeatRegressor(verbose=1, feateng_steps=3, n_jobs=24)
afreg.fit(x_train, y_train)

ValueError                                Traceback (most recent call last)
Input In [15], in <cell line: 2>()
      1 afreg = AutoFeatRegressor(verbose=1, feateng_steps=1, n_jobs=24)
----> 2 afreg.fit(x_train, y_train)

File /app/conda/b2b-latest/lib/python3.8/site-packages/autofeat/autofeat.py:422, in AutoFeatModel.fit(self, X, y)
    420     print("[AutoFeat] Warning: This just calls fit_transform() but does not return the transformed dataframe.")
    421     print("[AutoFeat] It is much more efficient to call fit_transform() instead of fit() and transform()!")
--> 422 _ = self.fit_transform(X, y)  # noqa
    423 return self

File /app/conda/b2b-latest/lib/python3.8/site-packages/autofeat/autofeat.py:353, in AutoFeatModel.fit_transform(self, X, y)
    351 else:
    352     if self.problem_type in ("regression", "classification"):
--> 353         good_cols = select_features(
    354             df_subs, target_sub, self.featsel_runs, None, self.problem_type, self.n_jobs, self.verbose
    355         )
    356         # if no features were selected, take the original features
    357         if not good_cols:

File /app/conda/b2b-latest/lib/python3.8/site-packages/autofeat/featsel.py:245, in select_features(df, target, featsel_runs, keep, problem_type, n_jobs, verbose)
    241     def flatten_lists(l: list):
    242         return [item for sublist in l for item in sublist]
    244     selected_columns = flatten_lists(
--> 245         Parallel(n_jobs=n_jobs, verbose=100 * verbose)(delayed(run_select_features)(i) for i in range(featsel_runs))
    246     )
    248 if selected_columns:
    249     selected_columns = Counter(selected_columns)

File /app/conda/b2b-latest/lib/python3.8/site-packages/joblib/parallel.py:1944, in Parallel.__call__(self, iterable)
   1938 # The first item from the output is blank, but it makes the interpreter
   1939 # progress until it enters the Try/Except block of the generator and
   1940 # reach the first `yield` statement. This starts the aynchronous
   1941 # dispatch of the tasks to the workers.
   1942 next(output)
-> 1944 return output if self.return_generator else list(output)

File /app/conda/b2b-latest/lib/python3.8/site-packages/joblib/parallel.py:1587, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1584     yield
   1586     with self._backend.retrieval_context():
-> 1587         yield from self._retrieve()
   1589 except GeneratorExit:
   1590     # The generator has been garbage collected before being fully
   1591     # consumed. This aborts the remaining tasks if possible and warn
   1592     # the user if necessary.
   1593     self._exception = True

File /app/conda/b2b-latest/lib/python3.8/site-packages/joblib/parallel.py:1691, in Parallel._retrieve(self)
   1684 while self._wait_retrieval():
   1685 
   1686     # If the callback thread of a worker has signaled that its task
   1687     # triggered an exception, or if the retrieval loop has raised an
   1688     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1689     # worker traceback.
   1690     if self._aborting:
-> 1691         self._raise_error_fast()
   1692         break
   1694     # If the next job is not ready for retrieval yet, we just wait for
   1695     # async callbacks to progress.

File /app/conda/b2b-latest/lib/python3.8/site-packages/joblib/parallel.py:1726, in Parallel._raise_error_fast(self)
   1722 # If this error job exists, immediatly raise the error by
   1723 # calling get_result. This job might not exists if abort has been
   1724 # called directly or if the generator is gc'ed.
   1725 if error_job is not None:
-> 1726     error_job.get_result(self.timeout)

File /app/conda/b2b-latest/lib/python3.8/site-packages/joblib/parallel.py:735, in BatchCompletionCallBack.get_result(self, timeout)
    729 backend = self.parallel._backend
    731 if backend.supports_retrieve_callback:
    732     # We assume that the result has already been retrieved by the
    733     # callback thread, and is stored internally. It's just waiting to
    734     # be returned.
--> 735     return self._return_or_raise()
    737 # For other backends, the main thread needs to run the retrieval step.
    738 try:

File /app/conda/b2b-latest/lib/python3.8/site-packages/joblib/parallel.py:753, in BatchCompletionCallBack._return_or_raise(self)
    751 try:
    752     if self.status == TASK_ERROR:
--> 753         raise self._result
    754     return self._result
    755 finally:

ValueError: Input X contains NaN.
LassoLarsCV does not accept missing values encoded as NaN natively.

**Comment by sauravsingh243** [comment]
PS:
I already checked NaN in my x_train
x_train.isna().values.any() is giving me False.

**Comment by cod3licious** [comment]
@sauravsingh243 please provide some code + data to reproduce this issue, incl. the library versions you're using.

**Comment by sauravsingh243** [comment]
@cod3licious can you give me your email?

**Comment by sarah-allec** [comment]
Never mind - I took a look at [this issue](https://github.com/cod3licious/autofeat/issues/32) and removing zero-variance features worked for me.
