### ISSUE TITLE
Documentation Enhancement for getting model, features, coefficients

### ISSUE THREAD

**Issue by Nempickaxe** [cod3licious/autofeat#41]
---
name: Documentation Enhancement
about: Request for clarification or improvement in the documentation

---

**Description of the Issue**

I've been using the `autofeat` library and encountered difficulties in obtaining the final model, model features, and coefficients as described in the library's documentation.

- The `model.get_model()`, `model.get_model_features()`, and `model.get_model_coefs()` methods do not seem to work as expected.
- I would appreciate clarification on how to access the final model, its features, and coefficients or an update to the documentation.

**Additional Information**

- Python Version: [e.g., Python 3.9]
- `autofeat` Library Version: [e.g., autofeat 2.1.2]

**Note to Maintainers**

Please consider updating the documentation or providing guidance on how to access the final model, features, and coefficients using the `AutoFeatRegressor` class. This would greatly help users in understanding and utilizing the library effectively.

Thank you for your attention to this matter.

**Comment by cod3licious** [comment]
@Nempickaxe I'm a bit confused... what gave you the impression, that the models had a `get_model` function or any of the other functions that you mentioned there?

**Comment by janezlapajne** [comment]
@cod3licious is it possible, however, to somehow get which features were selected? For example, to get the names of the features ?
