### ISSUE TITLE
AutoFeatLight.fit_trasnform() take 2 positional arguments 3 given

### ISSUE THREAD

**Issue by ahmed-kamal91** [cod3licious/autofeat#42]
I'm already put 2 arguments:  AutoFeatLight.fit_trasnform(X,y).
I tried to put Dataframe, then 2Darray. then try to make X has one feature, then both X and y are one dimensional array.
No way. all of them give me the same error

**Comment by ahmed-kamal91** [comment]
please, anyone help

**Comment by cod3licious** [comment]
Can you give a bit more details on what you're actually passing as X and y and what the exact error message is?
X should be a 2D matrix or dataframe, y a vector/series.
