### ISSUE TITLE
Multiclass Classification Problem

### ISSUE THREAD

**Issue by Muhammad4hmed** [cod3licious/autofeat#6]
I know this is only for regression, but the approach which I am thinking of is, I fit_transform the entire data frame containing multi labels in 'y' column and feed the obtained data frame to some other model. will it work? or is there any other better approach? (provide code example if possible).

thanks.

**Comment by cod3licious** [comment]
As of version 1.0.0, there are two autofeat models available, `AutoFeatRegressor` and `AutoFeatClassifier` for regression and classification problems respectively, so please update with `pip install --upgrade autofeat` and use these models instead. The classification model covers multiclass problems as well; use it just like a sklearn classifier.
