### ISSUE TITLE
can you clarify if categorical features can be used for your classifier   code?

### ISSUE THREAD

**Issue by Sandy4321** [cod3licious/autofeat#9]
can you clarify if categorical features can be used for your classifier   code?
and do you create combinatoric combinations for  categorical features

**Comment by cod3licious** [comment]
You can specify categorical features for any autofeat model, which will then be one-hot encoded. If you update the autofeat library again (to version 1.1.0), these categorical features will now also be used in the feature engineering process. (Let me know if you encounter any problems there, I haven't tested this on a lot of datasets with categorical features.)
